### ISSUE TITLE
Implement ildg format

### ISSUE THREAD

**Issue by lukas-mazur** [LatticeQCD/SIMULATeQCD#18]
Implement the ildg format

**Comment by clarkedavida** [comment]
With dc226d47a512f02a3733b66ddc9f3b0fe0390528 I have added some documentation for this.

**Comment by clarkedavida** [comment]
In the coming weeks there are still some small adjustments that have to be made to this. Right now we can read and write in LIME format. We can also read and write configurations in the same way as QUDA. The goal is to be able to eventually read in a LIME file saved in the appropriate ILDG format, making sure the messages are in the correct order. This will not take much time once one has an example configuration.

**Comment by clarkedavida** [comment]
All that is actually left to do from our end is
- [ ] change the XML labels to be the correct ILDG labels
- [ ] get the message begin and message end flags correct (thanks to Hubert Simma for noticing this)
- [ ] update the tests correspondingly

This will make it so that we can no longer directly read a QUDA configuration, but I think that is okay. All that matters is that we correctly read and write ILDG configurations, which we in PUNCH4NFDI are writing tests for right now.
