### ISSUE TITLE
Chiral condensate measurement for imaginary mu

### ISSUE THREAD

**Issue by jishnuxx** [LatticeQCD/SIMULATeQCD#48]
Chiral condensate measurement needs to be modified for imaginary mu(mu!=0).

**Comment by clarkedavida** [comment]
The fix has been made, but it would be nice if we had some reference chiral condensate. I guess we can't compare with the parallelgpucode directly because it is not doing exactly the same thing as SIMULATeQCD still. We could try the analytic continuation test, but of course that will not be very precise. Jishnu, do you have any other ideas?

**Comment by clarkedavida** [comment]
A statistical comparison yields
bielefeldGPUCode: psibar-psi =  0.06580(92)
SIMULATeQCD: psibar-psi =  0.06541(98)

I don't think it is possible to do a more rigorous comparison than this, at least not without investing an inordinate amount of time. The above comparison is as rigorous as any physics comparison would be.

- [ ] Implement a link-by-link test, which assumes current results are correct.

We will use the link-by-link test going forward.

**Comment by clarkedavida** [comment]
This is now done. When it's merged into the main branch I'll close this issue.
